### ISSUE TITLE
Do polling to revoke card when it's used in all doors

### ISSUE THREAD

**Issue by rayriffy** [creatorsgarten/garden-gate#3]
Just having timeout assume is just fine, but ideally it should be revoked after it has been used in all access doors. here's simplest workflow that i have in mind

![IMG_0310](https://github.com/creatorsgarten/garden-gate/assets/22584594/64edcb90-ba79-4aa4-b055-40a7095281fa)

**Comment by dtinth** [comment]
right now the [cleanup process works on a per-door basis](https://github.com/creatorsgarten/garden-gate/blob/b048093af802aea88de0b898cff8f6544d0a2ff6/src/index.ts#L36-L70), therefore, it is also possible to revoke on a per-door basis. so there is no coordination needed to check if a card has been used in all doors — if a card is used on door 1, we can deactivate that card on just door 1.

**Comment by rayriffy** [comment]
should be in 61ffbe2a89778f735ad6f8cbd78d617450a9374e

**Comment by dtinth** [comment]
@rayriffy i deployed the code to the simulator testing environment, it works krub!
