### ISSUE TITLE
Revoke existing card before requesting a new one

### ISSUE THREAD

**Issue by rayriffy** [creatorsgarten/garden-gate#5]
Handle scenario where user request to generate a new card again, while existing card still neither expiring nor being used. In any-case, old existing card that not expired yet should be revoked first before getting a new one.

**Comment by rayriffy** [comment]
Should be in 2015df52b60dd64e8bd14374c2cb14c74d3969eb. Tested in sim, will check real access door

**Comment by dtinth** [comment]
@rayriffy i deployed the code to the simulator testing environment, it works krub!
